name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: fritzregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_TOKEN }}    
    - name: Build the Docker image
      run: docker build --platform linux/arm --file Fritz.DemoPi/Dockerfile-ARM32 --tag fritzregistry.azurecr.io/fritz.demopi:$(date +%s) --tag fritzregistry.azurecr.io/fritz.demopi:latest .
    - name: Push the Docker image
      run: docker push fritzregistry.azurecr.io/fritz.demopi -a
