name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: fritzregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_TOKEN }}    
    - name: Get current date
      run: echo ::set-env name=DATE::$(date +%s)
    - name: Build the Docker image
      run: |
        dotnet publish --arch arm \
          -p PublishProfile=DefaultContainer \
          -p ContainerRegistry=fritzregistry.azurecr.io \
          -p ContainerImageTags='"latest;${{ env.DATE }}"' \
          -p ContainerFamily=alpine
